### ISSUE TITLE
Heligeom.py binding issues 

### ISSUE THREAD

**Issue by SafiaSafa** [ptools/ptools-legacy#76]
**Problem**

```

python ~/ptools/ptools-dev/Heligeom/heligeom.py 2GLS_A.pdb 2GLS_B.pdb

Traceback (most recent call last):
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 180, in <module>
    hp = heliAnalyze(mono1, mono2, True)
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 116, in heliAnalyze
    dmin, dmax = distAxis(mono1, hp)
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 27, in distAxis
    rigSize = rig.Size()
AttributeError: '_ptools.Rigidbody' object has no attribute 'Size'

```
```

python ~/ptools/ptools-dev/Heligeom/heligeom.py 2GLS_A.pdb 2GLS_B.pdb

Traceback (most recent call last):
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 180, in <module>
    hp = heliAnalyze(mono1, mono2, True)
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 116, in heliAnalyze
    dmin, dmax = distAxis(mono1, hp)
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 32, in distAxis
    c = rig.GetCoords(i)
AttributeError: '_ptools.Rigidbody' object has no attribute 'GetCoords'

```
```

python ~/ptools/ptools-dev/Heligeom/heligeom.py 2GLS_A.pdb 2GLS_B.pdb

Traceback (most recent call last):
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 180, in <module>
    hp = heliAnalyze(mono1, mono2, True)
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 116, in heliAnalyze
    dmin, dmax = distAxis(mono1, hp)
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 38, in distAxis
    d = Norm(VectProd(vect, hp.unitVector))
NameError: global name 'Norm' is not defined

```

```

python ~/ptools/ptools-dev/Heligeom/heligeom.py 2GLS_A.pdb 2GLS_B.pdb 6

Traceback (most recent call last):
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 184, in <module>
    final = heliConstruct(mono1, hp, N, Z, "print")
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 137, in heliConstruct
    final = extend(hp, mono1, N, Z)
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 98, in extend
    monoTest = changeChain(monoTest, string.ascii_uppercase[i % 26])
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 67, in changeChain
    at.SetChainId(letter)
AttributeError: '_ptools.Atomproperty' object has no attribute 'SetChainId'


```

```

python ~/ptools/ptools-dev/Heligeom/heligeom.py 2GLS_A.pdb 2GLS_B.pdb 6

 File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 184, in <module>
    final = heliConstruct(mono1, hp, N, Z, "print")
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 137, in heliConstruct
    final = extend(hp, mono1, N, Z)
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 98, in extend
    monoTest = changeChain(monoTest, string.ascii_uppercase[i % 26])
  File "/ibpc/pluton/safatahar/ptools/ptools-dev/Heligeom/heligeom.py", line 68, in changeChain
    rig.SetAtomProperty(i, at)
AttributeError: '_ptools.Rigidbody' object has no attribute 'SetAtomProperty'



```
**Solution**
* Replace *Size* by *len()*
* Replace *GetCoords* by *getCoords*
* Replace *Norm* by *norm*

[heligeom.tar.gz](https://github.com/ptools/ptools/files/842018/heligeom.tar.gz)

**Comment by benoistlaurent** [comment]
* `Rigidbody.size()` implemented in 899b350a
* Use  `Rigidbody. getCoords()` instead of `Rigidbody. GetCoords()`
* Use  `ptools.norm()` instead of `ptools.Norm()`
* Use  `Atomproperty.chainId = ...` instead of `Atomproperty.SetChainID(string)`
* `Rigidbody.SetAtomProperty` implemented in 5708a8c
