### ISSUE TITLE
The .red file returned by the startligand.py function does not have a HEADER 

### ISSUE THREAD

**Issue by SafiaSafa** [ptools/ptools-legacy#78]
*Problem*
```

ptools attract -r coreL1.red -l ligand_127_42.red --ref=ligand.red -s > single_movie.att


Traceback (most recent call last):
  File "/ibpc/pluton/safatahar/vptools/bin/ptools", line 9, in <module>
    load_entry_point('ptools==1.2', 'console_scripts', 'ptools')()
  File "build/bdist.linux-x86_64/egg/ptools/scripts/ptools_cli.py", line 30, in main
  File "build/bdist.linux-x86_64/egg/ptools/scripts/attract_cmd.py", line 149, in run
  File "build/bdist.linux-x86_64/egg/ptools/io.py", line 474, in check_ff_version_match
    
  File "build/bdist.linux-x86_64/egg/ptools/io.py", line 524, in read_forcefield_from_reduced
    
  File "build/bdist.linux-x86_64/egg/ptools/io.py", line 517, in get_ffname
    
  File "build/bdist.linux-x86_64/egg/ptools/io.py", line 508, in get_header_tokens
    
  File "build/bdist.linux-x86_64/egg/ptools/io.py", line 504, in get_header_line
    
IOError: ligand_127_42.red: reduced PDB file first line must be a HEADER line specifying the chosen force field (['ATTRACT1', 'ATTRACT2', 'SCORPION'])
```

[startligand.tar.gz](https://github.com/ptools/ptools/files/841982/startligand.tar.gz)

[startligand.py.tar.gz](https://github.com/ptools/ptools/files/842028/startligand.py.tar.gz)

**Comment by benoistlaurent** [comment]
Solve this and put `startligand.py` in `scripts`?

**Comment by chantalprevost** [comment]
Safia has corrected  startligand.py. The new version will be added to the "scripts" directory
