### ISSUE TITLE
Problem with the option --ignore-error of reduce.py

### ISSUE THREAD

**Issue by SafiaSafa** [ptools/ptools-legacy#79]
*Problem*

```

ptools reduce --ignore-error all -o receptor_adn.red receptor_adn.pdb attract1 --prot


WARNING: This exception was raised while reducing all-atom model:
IncompleteBeadError: in residue LYS:436 in bead 'CB'
    expected atoms: ['CG']
    found atoms: []
    missing atoms: ['CG']
WARNING: Ignoring this exception as requested.
Traceback (most recent call last):
  File "/ibpc/pluton/safatahar/vptools/bin/ptools", line 9, in <module>
    load_entry_point('ptools==1.2', 'console_scripts', 'ptools')()
  File "build/bdist.linux-x86_64/egg/ptools/scripts/ptools_cli.py", line 30, in main
  File "build/bdist.linux-x86_64/egg/ptools/scripts/reduce_cmd.py", line 121, in run
  File "build/bdist.linux-x86_64/egg/ptools/reduce.py", line 504, in print_output_model
  File "build/bdist.linux-x86_64/egg/ptools/reduce.py", line 504, in <genexpr>
  File "build/bdist.linux-x86_64/egg/ptools/reduce.py", line 85, in toatom
  File "build/bdist.linux-x86_64/egg/ptools/reduce.py", line 69, in coords
ZeroDivisionError: float division by zero
```

Maybe it is because of the fact that reduce.py tries to make a bead when it is impossible, so it "*blocks*" when ordering?
>the option --ignore-error has too many arguments, is-it possible to have "all" by default?

[reduce.py.tar.gz](https://github.com/ptools/ptools/files/843775/reduce.py.tar.gz)
[receptor.pdb.tar.gz](https://github.com/ptools/ptools/files/843777/receptor.pdb.tar.gz)

**Comment by benoistlaurent** [comment]
Problem is when no atoms have been found to form the bead.
The ``ZeroDivisionError`` occurs when calculating the bead coordinates: you have to divide by the number of atoms constituting the bead, which in this case is 0.

**Suggested solution**
Two solutions are to be considered:

1. Ignore the residue when error occurs
2. Ignore bead when error occurs

Chantal, any advice?

**Comment by chantalprevost** [comment]
I checked the output of PTools 1.0, only the bead is ignored.
                      **Solution n° 2**
