### ISSUE TITLE
Tutorial binding issues

### ISSUE THREAD

**Issue by SafiaSafa** [ptools/ptools-legacy#80]
*Problem*

```
python
>>>from ptools import *
>>> pdb = Rigidbody("1BTA.pdb")
>>> pdb.CenterToOrigin()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_ptools.Rigidbody' object has no attribute 'CenterToOrigin'

>>> pdb.PrintPDB()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_ptools.Rigidbody' object has no attribute 'PrintPDB'

>>> at = pdb.CopyAtom(2)
>>> new_XYZ = Coord3D(2.1,3.9,5.5)
>>> at.SetCoords(new_XYZ)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_ptools.Atom' object has no attribute 'SetCoords'

>>>at.atomElement
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_ptools.Atom' object has no attribute 'atomElement'

>>>double=pdb+pdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: '_ptools.Rigidbody' and '_ptools.Rigidbody'

```
[1BTA.pdb.tar.gz](https://github.com/ptools/ptools/files/843835/1BTA.pdb.tar.gz)

**Comment by benoistlaurent** [comment]
`center_to_origin` implemented in aad81d0
`print_pdb` implemented in 6b97852
`set_coords` implemented in 5168620
`atomElement` bindings implemented in 89636cb
`operator +` implemented in 899b350
